apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: workload
spec:
  gatewayClassName: approuting-istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: workload.example.com
      allowedRoutes:
        namespaces:
          from: Same
